version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_DATABASE: g3y_development

  web:
    build: .
    entrypoint:
      - dockerize
      - -timeout
      - 120s
      - -wait
      - tcp://db:3306
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/g3y
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DOCKER_DB_HOST: db
      DOCKER_WEBPACKER_HOST: frontend

  frontend:
    build: .
    command: bin/webpack-dev-server
    volumes:
      - .:/g3y
    ports:
      - "3035:3035"
