version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
        environment:
          RAILS_ENV: test

      - image: circleci/mysql:5.7.28
        environment:
          MYSQL_DATABASE: g3y_test
          MYSQL_USER: root

      - image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        environment:
          - cluster.name: elasticsearch
          - xpack.security.enabled: false
          - transport.host: localhost
          - network.host: 127.0.0.1
          - http.port: 9200
          - discovery.type: single-node

    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1

      - ruby/bundle-install

      - run:
          name: Create database
          command: RAILS_ENV=test bundle exec rails db:create
      - run:
          name: Setup database
          command: RAILS_ENV=test bin/rails db:schema:load --trace
      - run:
          name: Rubocop
          command: bundle exec rubocop
      - restore_cache:
          name: yarn restore cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: yarn install
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save yarn packages cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: ESLint
          command: yarn run eslint
      - run:
          name: stylelint
          command: yarn run stylelint

      - run:
          name: Wait for Elasticsearch
          command: dockerize -wait tcp://localhost:9200 -timeout 1m
      - run:
          name: RSpec
          command: bundle exec rspec spec/
